config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'receipts#index'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :receipts
  resources :receipts do
    post 'edit' => 'receipts#edit', as: :edit
  end

  resources :receipt_details, only: [], param: :index do
    member do
      delete '(:id)' => 'receipt_details#destroy', as: ''
      post '/' => 'receipt_details#create'
    end
  end
  resources :receipt_prices, only: [], param: :index do
    member do
      delete '(:id)' => 'receipt_prices#destroy', as: ''
      post '/' => 'receipt_prices#create'
    end
  end
  resources :receipt_discounts, only: [], param: :index do
    member do
      delete '(:id)' => 'receipt_discounts#destroy', as: ''
      post '/' => 'receipt_discounts#create'
    end
  end
  resources :accounts
  resources :receipt_categories

  get '/search', to: 'receipts#search_by_date'
  post '/search', to: 'receipts#search_by_date'

  get '/all_receipts', to: 'receipts#all_receipts'
  post '/all_receipts', to: 'receipts#all_receipts'
end

app/models/receipt_category.rb
class ReceiptCategory < ApplicationRecord
  has_many :receipt_details, inverse_of: :receipt_category
end

app/controllers/receipt_categories_controller.rb
class ReceiptCategoriesController < ApplicationController
  def index
    @receipt_categories = ReceiptCategory.all
  end

  def show
    @receipt_category = ReceiptCategory.find(params[:id])
  end

  def new
    @receipt_category = ReceiptCategory.new
  end

  def create
    @receipt_category = ReceiptCategory.new(receipt_category_params)
    if @receipt_category.save
      redirect_to action: "index"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def receipt_category_params
    params.require(:receipt_category).permit(:name)
  end
end

app/helpers/receipt_categories_helper.rb
module ReceiptCategoriesHelper

  def id_from_name(name)
    ReceiptCategory.where(:name => name).collect(&:id)[0]
  end
end

app/views/receipt_categories/index.html.erb
<h1> Receipt Categories </h1>

<%= link_to "Add Receipt category", new_receipt_category_path %><br>
<%= link_to "Receipts", receipts_path %>

<table>
  <tr>
    <th> Name </th>
  </tr>
  <% @receipt_categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
    </tr>
  <% end %>
</table>

app/views/receipt_categories/new.html.erb
<h1>New Receipt Category</h1>

<%= form_with model: @receipt_category do |form|%>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @receipt_category.errors.full_messages_for(:date).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<p><%= link_to "Home", root_path %></p>