config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'receipts#index'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :receipts
  resources :receipts do
    post 'edit' => 'receipts#edit', as: :edit
  end

  resources :receipt_details, only: [], param: :index do
    member do
      delete '(:id)' => 'receipt_details#destroy', as: ''
      post '/' => 'receipt_details#create'
    end
  end
  resources :receipt_prices, only: [], param: :index do
    member do
      delete '(:id)' => 'receipt_prices#destroy', as: ''
      post '/' => 'receipt_prices#create'
    end
  end
  resources :receipt_discounts, only: [], param: :index do
    member do
      delete '(:id)' => 'receipt_discounts#destroy', as: ''
      post '/' => 'receipt_discounts#create'
    end
  end
  resources :accounts
  resources :receipt_categories

  get '/search', to: 'receipts#search_by_date'
  post '/search', to: 'receipts#search_by_date'

  get '/all_receipts', to: 'receipts#all_receipts'
  post '/all_receipts', to: 'receipts#all_receipts'
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  has_many :receipt_details, inverse_of: :receipt, dependent: :delete_all
  has_many :receipt_prices, inverse_of: :receipt, dependent: :delete_all
  has_many :receipt_discounts, inverse_of: :receipt, dependent: :delete_all
  has_many :accounts, through: :receipt_prices

  validates :date, presence: true
  validates :is_income, presence: false
  validates :comment, presence: true
  validates :location, presence: false
  validates :store, presence: false

  # Ensure at least one associated record for prices & details
  validates :receipt_prices, presence: true
  validates :receipt_details, presence: true

  accepts_nested_attributes_for :receipt_details, allow_destroy: true#, reject_if: lambda {|attributes| attributes['pa_word'].blank?}
  accepts_nested_attributes_for :receipt_prices, allow_destroy: true
  accepts_nested_attributes_for :receipt_discounts, allow_destroy: true

  validates_associated :receipt_prices

  validate :total_equals_details_prices_and_discounts
  validate :accounts_uniqueness
  validate :matching_categories

  before_save :normalize_blank_values

  def normalize_blank_values
    attributes.each do |column, _|
      self[column].present? || self[column] = nil if column.in? %w[store location]
    end
  end

  def total_equals_details_prices_and_discounts
    # Check that every price is valid for both list
    return unless receipt_prices.map(&:price).map(&:present?).all?
    return unless receipt_details.map(&:price).map(&:present?).all?
    return unless receipt_discounts.map(&:discount).map(&:present?).all?

    valid_receipt_prices = receipt_prices.to_a.select { |r_price| not r_price._destroy.present?}
    valid_receipt_details = receipt_details.to_a.select { |r_detail| not r_detail._destroy.present?}
    valid_receipt_discounts = receipt_discounts.to_a.select { |r_detail| not r_detail._destroy.present?}

    # For details, map price and quantity column and perform the multiplication
    price_to_quantity = valid_receipt_details.map(&:price).zip(valid_receipt_details.map(&:quantity)).map { |p, q| p * q }
    # Sum everything
    details_total = (price_to_quantity.sum).round(2)
    prices_total = (valid_receipt_prices.map(&:price).sum).round(2)
    # Set discount total to 0 if no discounts are present
    discounts_total = valid_receipt_discounts.present? ? (valid_receipt_discounts.map(&:discount).sum).round(2) : 0

    if (details_total - discounts_total).round(2) != prices_total
      errors.add(
        :base,
        "Totals do not match (Details : #{details_total}, Discounts : #{discounts_total}, Accounts : #{prices_total})"
      )
    end
  end

  def accounts_uniqueness
    valid_receipt_prices = receipt_prices.to_a.select { |r_price| not r_price._destroy.present?}
    accounts_id = valid_receipt_prices.map(&:account_id)
    unique_accounts_id = accounts_id.uniq
    return unless unique_accounts_id.size != accounts_id.size

    errors.add(:base, 'Some accounts are referenced more than once.')
  end

  def matching_categories
    valid_categories = receipt_details.to_a.pluck(:receipt_category_id)
    discount_categories = receipt_discounts.to_a.pluck(:receipt_category_id)
    return if (discount_categories - valid_categories).empty?

    errors.add(:base, 'Discounts categories does not match receipt details\'s categories.')
  end

  def receipt_details_subtotal
    receipt_details.pluck(:price, :quantity).map { |p, q| p * q }.sum
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def index
    @receipts = Receipt.all.includes(:receipt_details).order(date: :desc)
  end

  def all_receipts
    @receipts = Receipt.all.includes(:receipt_details).order(date: :desc)
  end

  def show
    @receipt = Receipt.joins(:accounts).find(params[:id])
  end

  def new
    @receipt = Receipt.new(receipt_details: [ReceiptDetail.new],
                           receipt_prices: [ReceiptPrice.new])
  end

  def search_by_date
    if params[:query_month]
      month = Receipt.sanitize_sql_like(params[:query_month].rjust(2, '0'))
      year = Receipt.sanitize_sql_like(params[:query_year])
      @receipts = Receipt.all.where("strftime('%m-%Y', date) = ? ", "#{month}-#{year}").order(date: :asc)
      unless @receipts.empty?
        categories_sum = Receipt.joins(:receipt_details => :receipt_category)
                                .where("strftime('%m-%Y', receipts.date) = ? ", "#{month}-#{year}")
                                .where('receipts.is_income is FALSE')
                                .group('receipt_categories.name')
                                .sum('receipt_details.price * receipt_details.quantity')
        discounts_sum = ReceiptDiscount.joins(:receipt, :receipt_category)
                                       .where("strftime('%m-%Y', receipts.date) = ? ", "#{month}-#{year}")
                                       .where('receipts.is_income is FALSE')
                                       .group('receipt_categories.name')
                                       .sum('receipt_discounts.discount')
        @total_per_category = categories_sum.merge(discounts_sum) { |_, v1, v2| (v1 - v2).round(2) }
      end
      @month = Date::MONTHNAMES[params[:query_month].to_i]
      @year = year
      render 'receipts/search_by_date'
    end
  end

  def destroy
    @receipt = Receipt.find(params[:id])
    @receipt.destroy

    redirect_to root_path
  end

  def edit
    @receipt = Receipt.find(params[:id])
    render 'receipts/edit'
  end

  def update
    @receipt = Receipt.find(params[:id])
    if @receipt.update(receipt_params) && @receipt.valid?
      redirect_to @receipt
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.update(
            'receipt_errors',
            partial: 'common/errors',
            locals: { errors_list: @receipt.errors }
          )
        end
      end
    end
  end

  def create
    @receipt = Receipt.new(receipt_params)
    if @receipt.save
      redirect_to action: 'index'
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.update(
            'receipt_errors',
            partial: 'common/errors',
            locals: { errors_list: @receipt.errors }
          )
        end
      end
    end
  end

  private

  def receipt_params
    params.require(:receipt).permit(:date, :comment, :is_income, :location, :store,
                                    receipt_details_attributes: [:id, :name, :price, :quantity,
                                                                 :receipt_category_id, '_destroy'],
                                    receipt_prices_attributes: [:id, :receipt_id, :account_id, :price, '_destroy'],
                                    receipt_discounts_attributes: [:id, :comment, :discount, :receipt_category_id, '_destroy']
    )
  end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper

  def total_sum_per_category
    Receipt.joins(:receipt_details => :receipt_category)
           .where('receipts.is_income is FALSE')
           .group('receipt_categories.name')
           .sum('receipt_details.price * receipt_details.quantity')
  end

  def total_discount_per_category
    ReceiptDiscount.joins(:receipt, :receipt_category)
                   .where('receipts.is_income is FALSE')
                   .group('receipt_categories.name')
                   .sum('receipt_discounts.discount')
  end

  def total_per_date_and_category
    total_cat_date = Receipt.joins(:receipt_details => :receipt_category)
                            .where('receipts.is_income is FALSE')
                            .group('receipt_categories.name, strftime("%m-%Y", receipts.date)')
                            .select("receipt_categories.name as 'r_name', receipts.date as 'r_date', sum(receipt_details.price * receipt_details.quantity) as 'total'")
    total_cat_discount_date = ReceiptDiscount.joins(:receipt, :receipt_category)
                                             .where('receipts.is_income is FALSE').group('receipt_categories.name, strftime("%m-%Y", receipts.date)')
                                             .select("receipt_categories.name as 'r_name', receipts.date as 'r_date', sum(receipt_discounts.discount) as 'total'")
    total_cat_date.each do |total|
      corr_disc = total_cat_discount_date.filter_map { |disc| disc[:total] if Date.parse(disc[:r_date]).strftime('%B %Y') == Date.parse(total[:r_date]).strftime('%B %Y') and disc[:r_name] == total[:r_name]}
      total[:total] = total[:total] - (corr_disc.empty? ? 0 : corr_disc[0])
    end
  end
end

app/views/receipts/_form.html.erb
<div id="receipt_errors"></div>

<%= form_with model: @receipt do |form|%>
  <div>
    <%= form.label :date %><br>
    <%= form.date_field :date, :value => @receipt.date.nil? ? Time.now.strftime("%Y-%m-%d") : @receipt.date %>
  </div>

  <div>
    <%= form.label :location %><br>
    <%= form.text_field :location, data: {autocomplete_source: Receipt.distinct.pluck(:location).compact.sort_by { |s| s.downcase }}%>
  </div>

  <div>
    <%= form.label :store %><br>
    <%= form.text_field :store, data: {autocomplete_source: Receipt.distinct.where.not(:location => nil).where.not(:store => nil).pluck(:store, :location).sort_by { |s, l| [l.downcase, s.downcase] }}%>
  </div>

  <div>
    <%= form.label :comment %><br>
    <%= form.text_field :comment %>
  </div>

  <div>
    <%= form.label :is_income %><br>
    <%= form.check_box :is_income %>
  </div>

  <table>
    <tr>
      <th>Account</th>
      <th>Price</th>
      <th>Remove ?</th>
    </tr>
    <tbody id="receipt_prices">
    <%= form.fields_for :receipt_prices do |price_form| %>
      <%= render "receipt_prices/new", form: price_form %>
    <% end %>
    </tbody>
  </table>
  <div id="receipt_prices_error_messages">
  </div>
  <%= form.submit "Add account",
                  formmethod: "post",
                  formaction: receipt_price_path(@receipt.receipt_prices.size),
                  formnovalidate: true,
                  id: "add-receipt-price"
  %>
  <table>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Category</th>
      <th>Remove ?</th>
    </tr>
    <tbody id="receipt_details">
    <%= form.fields_for :receipt_details do |detail_form| %>
      <%= render "receipt_details/new", form: detail_form %>
    <% end %>
    </tbody>
  </table>
  <div id="receipt_details_error_messages">
  </div>
  <%= form.submit "Add detail",
                  formmethod: "post",
                  formaction: receipt_detail_path(@receipt.receipt_details.size),
                  formnovalidate: true,
                  id: "add-receipt-detail"
  %>

  <table>
    <tr>
      <th>Comment</th>
      <th>Discount</th>
      <th>Remove ?</th>
    </tr>
    <tbody id="receipt_discounts">
    <%= form.fields_for :receipt_discounts do |discount_form| %>
      <%= render "receipt_discounts/new", form: discount_form %>
    <% end %>
    </tbody>
  </table>
  <div id="receipt_discounts_error_messages">
  </div>
  <%= form.submit "Add discount",
                  formmethod: "post",
                  formaction: receipt_discount_path(@receipt.receipt_discounts.size),
                  formnovalidate: true,
                  id: "add-receipt-discount"
  %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/receipts/all_receipts.html.erb
<h1>All Receipts</h1>
<%= link_to "Add receipt", new_receipt_path %><br>
<%= link_to "Search by month", search_url %><br>
<%= link_to "Accounts", accounts_path %>
<%= link_to "Categories", receipt_categories_path %><br>
<%= link_to "Overview", receipts_path %>
<table>
  <tr>
    <th>Date</th>
    <th>Location</th>
    <th>Store</th>
    <th>Comment</th>
    <th>Income</th>
    <th>Total</th>
  </tr>
  <% @receipts.each do |receipt|%>
    <tr>
      <td><%= receipt.date.strftime("%d-%m-%Y") %></td>
      <td><%= receipt.location.nil? ? sanitize("<em> N/A </em>") : receipt.location %></td>
      <td><%= receipt.store.nil? ? sanitize("<em> N/A </em>") : receipt.store %> </td>
      <td><%= receipt.comment %> </td>
      <td><%= receipt.is_income ? "Yes" : "No" %> </td>
      <td class="<%= receipt.is_income ? "income" : "expense" %>"><%= number_to_currency(receipt.receipt_prices.sum(:price), format: "%n") %> €</td>
      <td><%= link_to "Details", receipt %></td>
      <td><%= button_to "Edit", receipt_edit_path(receipt), :method => :get %></td>
      <td><%= button_to "Delete", receipt, :method => :delete, form: { data: { turbo_confirm: "Are you sure ?" } } %></td>
    </tr>
  <% end %>
</table>

app/views/receipts/edit.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'receipts_functions', 'data-turbolinks-track': true %>
<%= csrf_meta_tags %>

<h1>Edit Receipt <%= @receipt.id %></h1>

<%= render partial: 'receipts/form' %>

<p><%= link_to "Home", root_path %></p>

app/views/receipts/index.html.erb
<h1>Overview</h1>
<%= link_to "Add receipt", new_receipt_path %><br>
<%= link_to "Search by month", search_url %><br>
<%= link_to "Accounts", accounts_path %>
<%= link_to "Categories", receipt_categories_path %><br>
<%= link_to "All Receipts", all_receipts_path %>

<%= pie_chart total_sum_per_category.merge(total_discount_per_category) { |_, v1, v2| (v1 - v2).round(2) }, round: 2, zeros: true, suffix: " €" %>

<% total_cat_date = total_per_date_and_category %>

<% months = get_months_from_year(2022) %>
<% total_ordered = total_cat_date.to_a.group_by(&:r_name).map { |k, v| {name:k, data: v.map{ |v2| {Date.parse(v2.r_date).strftime('%B %Y') => v2.total}}.reduce(:merge)}}.sort_by{ |v| v[:data].keys.map { |k| k.to_date}.min }%>
<!-- Sort by name -->
<% total_ordered.sort_by! { |k| k[:name] } %>
<!-- Map each month/year values in first element to have ordered dates -->
<% total_ordered[0][:data] = months.filter_map { |k| [k, total_ordered[0][:data][k].nil? ? 0.0 : total_ordered[0][:data][k]] if Date.strptime(k, '%B %Y') <= Date.today}.to_h %>
<%= bar_chart total_ordered, stacked: true, round: 2, zeros: true, suffix: " €", height: "2000px" %>

app/views/receipts/new.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'receipts_functions', 'data-turbolinks-track': true %>
<%= csrf_meta_tags %>

<h1>New Receipt</h1>

<%= render partial: 'receipts/form' %>

<p><%= link_to "Home", root_path %></p>

app/views/receipts/search_by_date.html.erb
<%= form_with url: "/search", method: :post, data: { turbo: false } do |form| %>
  <%= form.label :query_month, "Search by month :" %>
  <% value = '' %>
  <% unless @month.nil?
       value = Date::MONTHNAMES.index(@month)
     end
  %>
  <%= form.number_field :query_month, min: 1, max: 12, step: 1, value: value %>
  <%= form.label :query_year, "Year :" %>
  <% year = Date.today.year %>
  <% unless @year.nil?
       year = @year
     end
  %>
  <!-- TODO Set min to min value in database -->
  <%= form.number_field :query_year, min: 2022, max: Date.today.year, step: 1, value: year%>
  <%= form.submit "Search" %>
<% end %>
<% unless @month.nil? or @year.nil?%>
  <% if @receipts.length <= 0 %>
    <h1>Cannot find receipts for <%= "#{@month} #{@year}" %></h1>
  <% else %>
    <h1>Searched <%= "#{@month} #{@year}" %></h1>
    <table>
      <tr>
        <th>Date</th>
        <th>Location</th>
        <th>Store</th>
        <th>Comment</th>
        <th>Income</th>
        <th>Total</th>
      </tr>
    <% @receipts.each do |receipt|%>
      <tr>
        <td><%= receipt.date.strftime("%d-%m-%Y") %></td>
        <td><%= receipt.location.nil? ? sanitize("<em> N/A </em>") : receipt.location %></td>
        <td><%= receipt.store.nil? ? sanitize("<em> N/A </em>") : receipt.store %> </td>
        <td><%= receipt.comment %> </td>
        <td><%= receipt.is_income ? "Yes" : "No" %> </td>
        <td class="<%= receipt.is_income ? "income" : "expense" %>"><%= number_to_currency(receipt.receipt_prices.sum(:price), format: "%n") %> €</td>
        <td><%= link_to "Details", receipt %></td>
        <td><%= button_to "Edit", receipt_edit_path(receipt), :method => :get %></td>
        <td><%= button_to "Delete", receipt, :method => :delete, form: { data: { turbo_confirm: "Are you sure ?" } } %></td>
      </tr>
    <% end %>
    </table>
  <% end %>
<% end %>
<%= link_to "Home", receipts_path %><br>

<% unless @total_per_category.nil?%>
  <%= pie_chart @total_per_category, round: 2, zeros: true, suffix: " €" %>
<% end %>

app/views/receipts/show.html.erb
<ul>
    <li>Date : <%= @receipt.date.strftime("%d-%m-%Y") %></li>
    <li>Location : <%= @receipt.location.nil? ? sanitize("<em> N/A </em>") : @receipt.location %> </li>
    <li>Store : <%= @receipt.store.nil? ? sanitize("<em> N/A </em>") : @receipt.store %> </li>
    <li>Comment : <%= @receipt.comment %> </li>
    <li>Income : <%= @receipt.is_income ? "Yes" : "No" %> </li>
    <% unless @receipt.receipt_prices.nil? %>
    <table>
      <tr>
        <th>Account</th>
        <th>Price</th>
      </tr>
      <% @receipt.receipt_prices.each do |r_price| %>
        <tr>
          <td><%= @receipt.accounts.find(r_price.account_id).name %></td>
          <td><%= number_to_currency(r_price.price, format: "%n") %> €</td>
        </tr>
      <% end %>
      <tr>
        <td colspan="2"> Total : <%= number_to_currency(@receipt.receipt_prices.sum(:price), format: "%n") %> €</td>
      </tr>
    </table>
    <% end %>
    <% unless @receipt.receipt_details.nil? %>
    <table>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Category</th>
      </tr>
      <% @receipt.receipt_details.each do |detail| %>
        <tr>
          <td><%= detail.name %></td>
          <td><%= number_to_currency(detail.price, format: "%n") %> €</td>
          <td><%= detail.quantity %></td>
          <td><%= detail.receipt_category.name %></td>
        </tr>
      <% end %>
      <tr>
        <td colspan="4"> Total : <%= number_to_currency(@receipt.receipt_details_subtotal, format: "%n") %> €</td>
      </tr>
    </table>
    <% end %>
    <% unless @receipt.receipt_discounts.nil? %>
    <table>
      <tr>
        <th>Comment</th>
        <th>Discount</th>
      </tr>
      <% @receipt.receipt_discounts.each do |discount| %>
        <tr>
          <td><%= discount.comment %></td>
          <td><%= number_to_currency(discount.discount, format: "%n") %> €</td>
          <td><%= discount.receipt_category.name %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</ul>

<%= link_to "All receipts", all_receipts_path %>