config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'receipts#index'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :receipts
  resources :receipts do
    post 'edit' => 'receipts#edit', as: :edit
  end

  resources :receipt_details, only: [], param: :index do
    member do
      delete '(:id)' => 'receipt_details#destroy', as: ''
      post '/' => 'receipt_details#create'
    end
  end
  resources :receipt_prices, only: [], param: :index do
    member do
      delete '(:id)' => 'receipt_prices#destroy', as: ''
      post '/' => 'receipt_prices#create'
    end
  end
  resources :receipt_discounts, only: [], param: :index do
    member do
      delete '(:id)' => 'receipt_discounts#destroy', as: ''
      post '/' => 'receipt_discounts#create'
    end
  end
  resources :accounts
  resources :receipt_categories

  get '/search', to: 'receipts#search_by_date'
  post '/search', to: 'receipts#search_by_date'

  get '/all_receipts', to: 'receipts#all_receipts'
  post '/all_receipts', to: 'receipts#all_receipts'
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :receipt_prices, inverse_of: :account, dependent: :destroy
  has_many :receipts, through: :receipt_prices
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to action: "index"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def account_params
    params.require(:account).permit(:name)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/index.html.erb
<h1>All Accounts</h1>
<%= link_to "Add account", new_account_path %><br>
<%= link_to "Receipts", receipts_path %>
<table>
  <tr>
    <th>Name</th>
  </tr>
  <% @accounts.each do |account|%>
    <tr>
      <td><%= account.name %></td>
    </tr>
  <% end %>
</table>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= form_with model: @account do |form|%>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @account.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<p><%= link_to "Home", root_path %></p>